# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/soumiksinha/Code/DunesTowerDefense

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/soumiksinha/Code/DunesTowerDefense

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/soumiksinha/Code/DunesTowerDefense/CMakeFiles /Users/soumiksinha/Code/DunesTowerDefense//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/soumiksinha/Code/DunesTowerDefense/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DunesTowerDefense

# Build rule for target.
DunesTowerDefense: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DunesTowerDefense
.PHONY : DunesTowerDefense

# fast build rule for target.
DunesTowerDefense/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/build
.PHONY : DunesTowerDefense/fast

#=============================================================================
# Target rules for targets named UnitTests

# Build rule for target.
UnitTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 UnitTests
.PHONY : UnitTests

# fast build rule for target.
UnitTests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/build
.PHONY : UnitTests/fast

external/glad/src/glad.o: external/glad/src/glad.c.o
.PHONY : external/glad/src/glad.o

# target to build an object file
external/glad/src/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/external/glad/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/external/glad/src/glad.c.o
.PHONY : external/glad/src/glad.c.o

external/glad/src/glad.i: external/glad/src/glad.c.i
.PHONY : external/glad/src/glad.i

# target to preprocess a source file
external/glad/src/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/external/glad/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/external/glad/src/glad.c.i
.PHONY : external/glad/src/glad.c.i

external/glad/src/glad.s: external/glad/src/glad.c.s
.PHONY : external/glad/src/glad.s

# target to generate assembly for a file
external/glad/src/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/external/glad/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/external/glad/src/glad.c.s
.PHONY : external/glad/src/glad.c.s

src/InputManager.o: src/InputManager.cpp.o
.PHONY : src/InputManager.o

# target to build an object file
src/InputManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/InputManager.cpp.o
.PHONY : src/InputManager.cpp.o

src/InputManager.i: src/InputManager.cpp.i
.PHONY : src/InputManager.i

# target to preprocess a source file
src/InputManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/InputManager.cpp.i
.PHONY : src/InputManager.cpp.i

src/InputManager.s: src/InputManager.cpp.s
.PHONY : src/InputManager.s

# target to generate assembly for a file
src/InputManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/InputManager.cpp.s
.PHONY : src/InputManager.cpp.s

src/MainGame.o: src/MainGame.cpp.o
.PHONY : src/MainGame.o

# target to build an object file
src/MainGame.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/MainGame.cpp.o
.PHONY : src/MainGame.cpp.o

src/MainGame.i: src/MainGame.cpp.i
.PHONY : src/MainGame.i

# target to preprocess a source file
src/MainGame.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/MainGame.cpp.i
.PHONY : src/MainGame.cpp.i

src/MainGame.s: src/MainGame.cpp.s
.PHONY : src/MainGame.s

# target to generate assembly for a file
src/MainGame.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/MainGame.cpp.s
.PHONY : src/MainGame.cpp.s

src/WaveManager.o: src/WaveManager.cpp.o
.PHONY : src/WaveManager.o

# target to build an object file
src/WaveManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/WaveManager.cpp.o
.PHONY : src/WaveManager.cpp.o

src/WaveManager.i: src/WaveManager.cpp.i
.PHONY : src/WaveManager.i

# target to preprocess a source file
src/WaveManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/WaveManager.cpp.i
.PHONY : src/WaveManager.cpp.i

src/WaveManager.s: src/WaveManager.cpp.s
.PHONY : src/WaveManager.s

# target to generate assembly for a file
src/WaveManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/WaveManager.cpp.s
.PHONY : src/WaveManager.cpp.s

src/engine/DataLoader.o: src/engine/DataLoader.cpp.o
.PHONY : src/engine/DataLoader.o

# target to build an object file
src/engine/DataLoader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/engine/DataLoader.cpp.o
.PHONY : src/engine/DataLoader.cpp.o

src/engine/DataLoader.i: src/engine/DataLoader.cpp.i
.PHONY : src/engine/DataLoader.i

# target to preprocess a source file
src/engine/DataLoader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/engine/DataLoader.cpp.i
.PHONY : src/engine/DataLoader.cpp.i

src/engine/DataLoader.s: src/engine/DataLoader.cpp.s
.PHONY : src/engine/DataLoader.s

# target to generate assembly for a file
src/engine/DataLoader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/engine/DataLoader.cpp.s
.PHONY : src/engine/DataLoader.cpp.s

src/engine/Renderer.o: src/engine/Renderer.cpp.o
.PHONY : src/engine/Renderer.o

# target to build an object file
src/engine/Renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/engine/Renderer.cpp.o
.PHONY : src/engine/Renderer.cpp.o

src/engine/Renderer.i: src/engine/Renderer.cpp.i
.PHONY : src/engine/Renderer.i

# target to preprocess a source file
src/engine/Renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/engine/Renderer.cpp.i
.PHONY : src/engine/Renderer.cpp.i

src/engine/Renderer.s: src/engine/Renderer.cpp.s
.PHONY : src/engine/Renderer.s

# target to generate assembly for a file
src/engine/Renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/engine/Renderer.cpp.s
.PHONY : src/engine/Renderer.cpp.s

src/engine/ResourceManager.o: src/engine/ResourceManager.cpp.o
.PHONY : src/engine/ResourceManager.o

# target to build an object file
src/engine/ResourceManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/engine/ResourceManager.cpp.o
.PHONY : src/engine/ResourceManager.cpp.o

src/engine/ResourceManager.i: src/engine/ResourceManager.cpp.i
.PHONY : src/engine/ResourceManager.i

# target to preprocess a source file
src/engine/ResourceManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/engine/ResourceManager.cpp.i
.PHONY : src/engine/ResourceManager.cpp.i

src/engine/ResourceManager.s: src/engine/ResourceManager.cpp.s
.PHONY : src/engine/ResourceManager.s

# target to generate assembly for a file
src/engine/ResourceManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/engine/ResourceManager.cpp.s
.PHONY : src/engine/ResourceManager.cpp.s

src/engine/VisionManager.o: src/engine/VisionManager.cpp.o
.PHONY : src/engine/VisionManager.o

# target to build an object file
src/engine/VisionManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/engine/VisionManager.cpp.o
.PHONY : src/engine/VisionManager.cpp.o

src/engine/VisionManager.i: src/engine/VisionManager.cpp.i
.PHONY : src/engine/VisionManager.i

# target to preprocess a source file
src/engine/VisionManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/engine/VisionManager.cpp.i
.PHONY : src/engine/VisionManager.cpp.i

src/engine/VisionManager.s: src/engine/VisionManager.cpp.s
.PHONY : src/engine/VisionManager.s

# target to generate assembly for a file
src/engine/VisionManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/engine/VisionManager.cpp.s
.PHONY : src/engine/VisionManager.cpp.s

src/entities/Base.o: src/entities/Base.cpp.o
.PHONY : src/entities/Base.o

# target to build an object file
src/entities/Base.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/entities/Base.cpp.o
.PHONY : src/entities/Base.cpp.o

src/entities/Base.i: src/entities/Base.cpp.i
.PHONY : src/entities/Base.i

# target to preprocess a source file
src/entities/Base.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/entities/Base.cpp.i
.PHONY : src/entities/Base.cpp.i

src/entities/Base.s: src/entities/Base.cpp.s
.PHONY : src/entities/Base.s

# target to generate assembly for a file
src/entities/Base.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/entities/Base.cpp.s
.PHONY : src/entities/Base.cpp.s

src/entities/Bee.o: src/entities/Bee.cpp.o
.PHONY : src/entities/Bee.o

# target to build an object file
src/entities/Bee.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/entities/Bee.cpp.o
.PHONY : src/entities/Bee.cpp.o

src/entities/Bee.i: src/entities/Bee.cpp.i
.PHONY : src/entities/Bee.i

# target to preprocess a source file
src/entities/Bee.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/entities/Bee.cpp.i
.PHONY : src/entities/Bee.cpp.i

src/entities/Bee.s: src/entities/Bee.cpp.s
.PHONY : src/entities/Bee.s

# target to generate assembly for a file
src/entities/Bee.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/entities/Bee.cpp.s
.PHONY : src/entities/Bee.cpp.s

src/entities/DuneWorm.o: src/entities/DuneWorm.cpp.o
.PHONY : src/entities/DuneWorm.o

# target to build an object file
src/entities/DuneWorm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/entities/DuneWorm.cpp.o
.PHONY : src/entities/DuneWorm.cpp.o

src/entities/DuneWorm.i: src/entities/DuneWorm.cpp.i
.PHONY : src/entities/DuneWorm.i

# target to preprocess a source file
src/entities/DuneWorm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/entities/DuneWorm.cpp.i
.PHONY : src/entities/DuneWorm.cpp.i

src/entities/DuneWorm.s: src/entities/DuneWorm.cpp.s
.PHONY : src/entities/DuneWorm.s

# target to generate assembly for a file
src/entities/DuneWorm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/entities/DuneWorm.cpp.s
.PHONY : src/entities/DuneWorm.cpp.s

src/entities/DungBeetle.o: src/entities/DungBeetle.cpp.o
.PHONY : src/entities/DungBeetle.o

# target to build an object file
src/entities/DungBeetle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/entities/DungBeetle.cpp.o
.PHONY : src/entities/DungBeetle.cpp.o

src/entities/DungBeetle.i: src/entities/DungBeetle.cpp.i
.PHONY : src/entities/DungBeetle.i

# target to preprocess a source file
src/entities/DungBeetle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/entities/DungBeetle.cpp.i
.PHONY : src/entities/DungBeetle.cpp.i

src/entities/DungBeetle.s: src/entities/DungBeetle.cpp.s
.PHONY : src/entities/DungBeetle.s

# target to generate assembly for a file
src/entities/DungBeetle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/entities/DungBeetle.cpp.s
.PHONY : src/entities/DungBeetle.cpp.s

src/entities/Enemy.o: src/entities/Enemy.cpp.o
.PHONY : src/entities/Enemy.o

# target to build an object file
src/entities/Enemy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/entities/Enemy.cpp.o
.PHONY : src/entities/Enemy.cpp.o

src/entities/Enemy.i: src/entities/Enemy.cpp.i
.PHONY : src/entities/Enemy.i

# target to preprocess a source file
src/entities/Enemy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/entities/Enemy.cpp.i
.PHONY : src/entities/Enemy.cpp.i

src/entities/Enemy.s: src/entities/Enemy.cpp.s
.PHONY : src/entities/Enemy.s

# target to generate assembly for a file
src/entities/Enemy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/entities/Enemy.cpp.s
.PHONY : src/entities/Enemy.cpp.s

src/entities/Projectile.o: src/entities/Projectile.cpp.o
.PHONY : src/entities/Projectile.o

# target to build an object file
src/entities/Projectile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/entities/Projectile.cpp.o
.PHONY : src/entities/Projectile.cpp.o

src/entities/Projectile.i: src/entities/Projectile.cpp.i
.PHONY : src/entities/Projectile.i

# target to preprocess a source file
src/entities/Projectile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/entities/Projectile.cpp.i
.PHONY : src/entities/Projectile.cpp.i

src/entities/Projectile.s: src/entities/Projectile.cpp.s
.PHONY : src/entities/Projectile.s

# target to generate assembly for a file
src/entities/Projectile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/entities/Projectile.cpp.s
.PHONY : src/entities/Projectile.cpp.s

src/entities/Sprayer.o: src/entities/Sprayer.cpp.o
.PHONY : src/entities/Sprayer.o

# target to build an object file
src/entities/Sprayer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/entities/Sprayer.cpp.o
.PHONY : src/entities/Sprayer.cpp.o

src/entities/Sprayer.i: src/entities/Sprayer.cpp.i
.PHONY : src/entities/Sprayer.i

# target to preprocess a source file
src/entities/Sprayer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/entities/Sprayer.cpp.i
.PHONY : src/entities/Sprayer.cpp.i

src/entities/Sprayer.s: src/entities/Sprayer.cpp.s
.PHONY : src/entities/Sprayer.s

# target to generate assembly for a file
src/entities/Sprayer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/entities/Sprayer.cpp.s
.PHONY : src/entities/Sprayer.cpp.s

src/entities/Sprite.o: src/entities/Sprite.cpp.o
.PHONY : src/entities/Sprite.o

# target to build an object file
src/entities/Sprite.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/entities/Sprite.cpp.o
.PHONY : src/entities/Sprite.cpp.o

src/entities/Sprite.i: src/entities/Sprite.cpp.i
.PHONY : src/entities/Sprite.i

# target to preprocess a source file
src/entities/Sprite.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/entities/Sprite.cpp.i
.PHONY : src/entities/Sprite.cpp.i

src/entities/Sprite.s: src/entities/Sprite.cpp.s
.PHONY : src/entities/Sprite.s

# target to generate assembly for a file
src/entities/Sprite.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/entities/Sprite.cpp.s
.PHONY : src/entities/Sprite.cpp.s

src/entities/Stinger.o: src/entities/Stinger.cpp.o
.PHONY : src/entities/Stinger.o

# target to build an object file
src/entities/Stinger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/entities/Stinger.cpp.o
.PHONY : src/entities/Stinger.cpp.o

src/entities/Stinger.i: src/entities/Stinger.cpp.i
.PHONY : src/entities/Stinger.i

# target to preprocess a source file
src/entities/Stinger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/entities/Stinger.cpp.i
.PHONY : src/entities/Stinger.cpp.i

src/entities/Stinger.s: src/entities/Stinger.cpp.s
.PHONY : src/entities/Stinger.s

# target to generate assembly for a file
src/entities/Stinger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/entities/Stinger.cpp.s
.PHONY : src/entities/Stinger.cpp.s

src/entities/Tower.o: src/entities/Tower.cpp.o
.PHONY : src/entities/Tower.o

# target to build an object file
src/entities/Tower.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/entities/Tower.cpp.o
.PHONY : src/entities/Tower.cpp.o

src/entities/Tower.i: src/entities/Tower.cpp.i
.PHONY : src/entities/Tower.i

# target to preprocess a source file
src/entities/Tower.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/entities/Tower.cpp.i
.PHONY : src/entities/Tower.cpp.i

src/entities/Tower.s: src/entities/Tower.cpp.s
.PHONY : src/entities/Tower.s

# target to generate assembly for a file
src/entities/Tower.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/entities/Tower.cpp.s
.PHONY : src/entities/Tower.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DunesTowerDefense.dir/build.make CMakeFiles/DunesTowerDefense.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

tests/test.o: tests/test.cpp.o
.PHONY : tests/test.o

# target to build an object file
tests/test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/tests/test.cpp.o
.PHONY : tests/test.cpp.o

tests/test.i: tests/test.cpp.i
.PHONY : tests/test.i

# target to preprocess a source file
tests/test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/tests/test.cpp.i
.PHONY : tests/test.cpp.i

tests/test.s: tests/test.cpp.s
.PHONY : tests/test.s

# target to generate assembly for a file
tests/test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/tests/test.cpp.s
.PHONY : tests/test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... DunesTowerDefense"
	@echo "... UnitTests"
	@echo "... external/glad/src/glad.o"
	@echo "... external/glad/src/glad.i"
	@echo "... external/glad/src/glad.s"
	@echo "... src/InputManager.o"
	@echo "... src/InputManager.i"
	@echo "... src/InputManager.s"
	@echo "... src/MainGame.o"
	@echo "... src/MainGame.i"
	@echo "... src/MainGame.s"
	@echo "... src/WaveManager.o"
	@echo "... src/WaveManager.i"
	@echo "... src/WaveManager.s"
	@echo "... src/engine/DataLoader.o"
	@echo "... src/engine/DataLoader.i"
	@echo "... src/engine/DataLoader.s"
	@echo "... src/engine/Renderer.o"
	@echo "... src/engine/Renderer.i"
	@echo "... src/engine/Renderer.s"
	@echo "... src/engine/ResourceManager.o"
	@echo "... src/engine/ResourceManager.i"
	@echo "... src/engine/ResourceManager.s"
	@echo "... src/engine/VisionManager.o"
	@echo "... src/engine/VisionManager.i"
	@echo "... src/engine/VisionManager.s"
	@echo "... src/entities/Base.o"
	@echo "... src/entities/Base.i"
	@echo "... src/entities/Base.s"
	@echo "... src/entities/Bee.o"
	@echo "... src/entities/Bee.i"
	@echo "... src/entities/Bee.s"
	@echo "... src/entities/DuneWorm.o"
	@echo "... src/entities/DuneWorm.i"
	@echo "... src/entities/DuneWorm.s"
	@echo "... src/entities/DungBeetle.o"
	@echo "... src/entities/DungBeetle.i"
	@echo "... src/entities/DungBeetle.s"
	@echo "... src/entities/Enemy.o"
	@echo "... src/entities/Enemy.i"
	@echo "... src/entities/Enemy.s"
	@echo "... src/entities/Projectile.o"
	@echo "... src/entities/Projectile.i"
	@echo "... src/entities/Projectile.s"
	@echo "... src/entities/Sprayer.o"
	@echo "... src/entities/Sprayer.i"
	@echo "... src/entities/Sprayer.s"
	@echo "... src/entities/Sprite.o"
	@echo "... src/entities/Sprite.i"
	@echo "... src/entities/Sprite.s"
	@echo "... src/entities/Stinger.o"
	@echo "... src/entities/Stinger.i"
	@echo "... src/entities/Stinger.s"
	@echo "... src/entities/Tower.o"
	@echo "... src/entities/Tower.i"
	@echo "... src/entities/Tower.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... tests/test.o"
	@echo "... tests/test.i"
	@echo "... tests/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

